Repository WalkingDogWithFriends/GaeManDa, pull requests merged in 2023-11, with the labels that each got.

#128 온보딩: 검색한 주소를 화면에 표시하는 기능을 구현
  GaeManda/.gitignore
  GaeManda/Projects/App/Info.plist
  GaeManda/Projects/App/Project.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutComponent.swift
  GaeManda/Projects/App/xcconfigs/GaeManda.shared.xcconfig
  GaeManda/Projects/Data/DTO/GeocodeDTO/GeocodeErrorResponseDTO.swift
  GaeManda/Projects/Data/DTO/GeocodeDTO/GeocodeResponseDTO.swift
  GaeManda/Projects/Data/GMDNetwork/NetworkError.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/GeocodingRepositoryImpl/GeocodingAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/GeocodingRepositoryImpl/GeocodingRepositoryImpl.swift
  GaeManda/Projects/Domain/Interfaces/Repository/GeocodeRepository.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/DetailAddressSettingUseCase.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/DetailAddressSettingUseCaseImpl.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/Views/LocationLoadButton.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/Views/NoticeLabel.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/DetailAddressSetting.swift
  GaeManda/Tuist/Dependencies.swift
  GaeManda/Tuist/ProjectDescriptionHelpers/TargetDependency+Extension.swift
Labels: feature

#133 약관 동의 바텀 시트 구현
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutComponent.swift
  GaeManda/Projects/Data/DTO/OnboardingDTO/TermsResponseDTO.swift
  GaeManda/Projects/Data/DataMapper/TermsMapper.swift
  GaeManda/Projects/Data/LocalStorage/Resources/Files/Terms.json
  GaeManda/Projects/Data/LocalStorage/Sources/CoreDataStorage/dummy.swift
  GaeManda/Projects/Data/LocalStorage/Sources/FileStorage/FileProvider.swift
  GaeManda/Projects/Data/LocalStorage/Sources/FileStorage/FileStorageError.swift
  GaeManda/Projects/Data/LocalStorage/Sources/FileStorage/FileType.swift
  GaeManda/Projects/Data/LocalStorage/Sources/FileStorage/FileURLConvertible.swift
  GaeManda/Projects/Data/LocalStorage/Sources/FileStorage/TargetType.swift
  GaeManda/Projects/Data/LocalStorage/Sources/FileStorage/TaskType.swift
  GaeManda/Projects/Data/Project.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/OnboardingRepositoryImpl/OnboardingFileAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/OnboardingRepositoryImpl/OnboardingRepositoryImpl.swift
  GaeManda/Projects/Domain/Entity/Terms.swift
  GaeManda/Projects/Domain/Interfaces/Repository/OnboardingRepository.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/TermsofUseUseCase.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/TermsofUseUseCaseImpl.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewModel.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/View/BottomSheet/TermsBottomSheetBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/View/BottomSheet/TermsBottomSheetInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/View/BottomSheet/TermsBottomSheetRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/View/BottomSheet/TermsBottomSheetViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/View/TermsOfUseCell/TermsOfUseButton.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/View/TermsOfUseCell/TermsOfUseCell.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/TermsBottomSheet.swift
  GaeManda/Tuist/ProjectDescriptionHelpers/TargetDependency+Extension.swift
Labels: feature

#140 네이밍 수정
  GaeManda/Makefile
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInInteractor.swift
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInRouter.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutComponent.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingViewModel.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserProfileSetting/UserProfileSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserProfileSetting/UserProfileSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserProfileSetting/UserProfileSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserProfileSetting/UserProfileSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/DogSetting.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/UserSetting.swift
Labels: style

#137 강아지 성격 설정 UI 변경
  GaeManda/Projects/DesignKit/Sources/Button/AddDogCharacterButton.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/View/SelectedDogCharacterCell.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingBuilder.swift
Labels: feature

#141 DogAPI / Repository / UseCase 수정
  GaeManda/Projects/App/Sources/AppRootComponent.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutBuilder.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutComponent.swift
  GaeManda/Projects/Data/DTO/DogDTO/CreateDog/CreateDogRequestDTO.swift
  GaeManda/Projects/Data/DTO/DogDTO/DogCharacter/DogCharacterResponseDTO.swift
  GaeManda/Projects/Data/DTO/DogDTO/DogRequestDTO.swift
  GaeManda/Projects/Data/DTO/DogDTO/DogSpecies/DogSpeciesResponseDTO.swift
  GaeManda/Projects/Data/DTO/DogDTO/FetchDogs/FetchDogsResponseDTO.swift
  GaeManda/Projects/Data/DTO/DogDTO/UpdateDog/UpdateDogRequestDTO.swift
  GaeManda/Projects/Data/DataMapper/DogDataMapper.swift
  GaeManda/Projects/Data/DataMapper/UserDataMapper.swift
  GaeManda/Projects/Data/LocalStorage/Resources/Files/DogSpecies.json
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogFileAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogRepositoryImpl.swift
  GaeManda/Projects/Domain/Entity/Dog.swift
  GaeManda/Projects/Domain/Entity/DogCharacter.swift
  GaeManda/Projects/Domain/Entity/Gender.swift
  GaeManda/Projects/Domain/Entity/User.swift
  GaeManda/Projects/Domain/Interfaces/Repository/DogReposiotry.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/GMDProfileUseCase.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/OnBoardingUseCase.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/GMDProfileUseCaseImpl.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/OnBoardingUseCaseImpl.swift
  GaeManda/Projects/Presentation/CorePresentation/Implementations/DogCharacters/DogCharacterPickerBuilder.swift
  GaeManda/Projects/Presentation/CorePresentation/Implementations/DogCharacters/DogCharacterPickerInteractor.swift
  GaeManda/Projects/Presentation/CorePresentation/Interfaces/DogCharacterPicker.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/GMDProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogProfileScrollView.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogsCollectionViewCell.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingViewModel.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingViewModel.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserProfileSetting/UserProfileSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/Widgets/OnBoardingView.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/DogSetting.swift
Labels: refactoring

#145 MultipartFormData 구현
  GaeManda/Projects/Data/GMDNetwork/EncodingType.swift
  GaeManda/Projects/Data/GMDNetwork/MultipartFormData/MultipartEncoding.swift
  GaeManda/Projects/Data/GMDNetwork/MultipartFormData/MultipartFormDataBody.swift
  GaeManda/Projects/Data/GMDNetwork/TargetType.swift
  GaeManda/Projects/Data/GMDNetwork/TaskType.swift
Labels: feature

#147 DogAPI 수정
  GaeManda/Projects/Core/GMDUtils/UIImageWrapper/UIImageWrapper.swift
  GaeManda/Projects/Data/DTO/DogDTO/CreateDog/CreateDogRequestDTO.swift
  GaeManda/Projects/Data/DTO/DogDTO/FetchDogs/FetchDogsResponseDTO.swift
  GaeManda/Projects/Data/DTO/DogDTO/UpdateDog/UpdateDogRequestDTO.swift
  GaeManda/Projects/Data/DTO/NewDogDTO/NewDogRequestDTO.swift
  GaeManda/Projects/Data/DataMapper/DogDataMapper.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogAPI.swift
  GaeManda/Projects/Domain/Entity/Dog.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileFirstSetting/DogProfileFirstSettingViewModel.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSecondSetting/DogProfileSecondSettingViewModel.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogProfileSetting/DogProfileSettingRouter.swift
Labels: refactoring
