Repository WalkingDogWithFriends/GaeManDa, pull requests merged in 2023-07, with the labels that each got.

#13 기능: 네트워크 모듈 구현
  GaeManda/Projects/App/Project.swift
  GaeManda/Projects/Data/GMDNetwork/EncodingType.swift
  GaeManda/Projects/Data/GMDNetwork/HTTP/BaseResponseDTO.swift
  GaeManda/Projects/Data/GMDNetwork/HTTP/HTTPHeader.swift
  GaeManda/Projects/Data/GMDNetwork/HTTP/HTTPHeaders.swift
  GaeManda/Projects/Data/GMDNetwork/HTTP/HTTPMethod.swift
  GaeManda/Projects/Data/GMDNetwork/NetworkError.swift
  GaeManda/Projects/Data/GMDNetwork/ParameterEncoding.swift
  GaeManda/Projects/Data/GMDNetwork/Provider.swift
  GaeManda/Projects/Data/GMDNetwork/Session.swift
  GaeManda/Projects/Data/GMDNetwork/TargetType.swift
  GaeManda/Projects/Data/GMDNetwork/TaskType.swift
  GaeManda/Projects/Data/GMDNetwork/URLRequestConvertible.swift
  GaeManda/Projects/Data/Project.swift
  GaeManda/Projects/Presentation/Settings/Interfaces/Dummy.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/Dummy.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/SignInBuilder.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/SignInInteractor.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/SignInRouter.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/SignInViewController.swift
  GaeManda/Projects/Presentation/SignIn/Interfaces/Dummy.swift
  GaeManda/Projects/Presentation/SignIn/Interfaces/SignInInterface.swift
  GaeManda/Tuist/ProjectDescriptionHelpers/TargetDependency+Extension.swift
Labels: feature

#20 Infra/#19
  GaeManda/Projects/App/Project.swift
  GaeManda/Projects/Core/Project.swift
  GaeManda/Projects/Data/Project.swift
  GaeManda/Projects/DesignKit/Project.swift
  GaeManda/Projects/Domain/Project.swift
  GaeManda/Tuist/ProjectDescriptionHelpers/Target+Extension.swift
  GaeManda/Tuist/ResourceSynthesizers/Assets.stencil
Labels: infra

#21 Refactoring/#18
  GaeManda/Projects/Core/GMDExtensions/UILabel+Extension.swift
  GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
  GaeManda/Projects/Core/GMDUtils/UIViewController+Utils.swift
  GaeManda/Projects/DesignKit/Project.swift
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/Green/Green100.colorset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/Green/Green60.colorset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/White/GMDWhite.colorset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images.xcassets/Contents.json
  GaeManda/Projects/DesignKit/Sources/OnBoardingTextField.swift
  GaeManda/Projects/DesignKit/Sources/OnBoardingTextView.swift
  GaeManda/Projects/DesignKit/Sources/UnderLineTextField.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseCell/TermsOfUseButton.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseCell/TermsOfUseCell.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/Widgets/OnBoardingButton.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/Widgets/OnBoardingView.swift
  GaeManda/Tuist/ResourceSynthesizers/Assets.stencil
  GaeManda/Tuist/ResourceSynthesizers/Colors.stencil
  GaeManda/Tuist/ResourceSynthesizers/Fonts.stencil
  GaeManda/Tuist/ResourceSynthesizers/Images.stencil
Labels: refactoring

#25 프로필 UI
  GaeManda/Projects/App/Project.swift
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInComponent.swift
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInTabBarController.swift
  GaeManda/Projects/App/Sources/LoggedIn/Widgets/TabBarButton.swift
  GaeManda/Projects/Core/GMDExtensions/Single+Extension.swift
  GaeManda/Projects/Core/GMDUtils/UIViewController+Utils.swift
  GaeManda/Projects/Data/DTO/Sources/DogDTO/DogRequestDTO.swift
  GaeManda/Projects/Data/DTO/Sources/DogDTO/DogResponseDTO.swift
  GaeManda/Projects/Data/DTO/Sources/Dummy.swift
  GaeManda/Projects/Data/DTO/Sources/UserDTO/UserRequestDTO.swift
  GaeManda/Projects/Data/DTO/Sources/UserDTO/UserResponseDTO.swift
  GaeManda/Projects/Data/Project.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogRepositoryImpl.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/Dummy.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/UserRepositoryImpl/UserAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/UserRepositoryImpl/UserRepositoryImpl.swift
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/Gray/Gray20.colorset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/Gray/Gray30.colorset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/Gray/Gray40.colorset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/Gray/Gray50.colorset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/Gray/Gray60.colorset/Contents.json
  GaeManda/Projects/Domain/Entity/Dog.swift
  GaeManda/Projects/Domain/Entity/User.swift
  GaeManda/Projects/Domain/Interfaces/Repository/DogReposiotry.swift
  GaeManda/Projects/Domain/Interfaces/Repository/Dummy.swift
  GaeManda/Projects/Domain/Interfaces/Repository/UserRepository.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/Dummy.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/UserProfileUseCase.swift
  GaeManda/Projects/Domain/Project.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/Dummy.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/UserProfileUseCaseImpl.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileBuilder.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogsCollectionViewCell.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/IndicatorView.swift
  GaeManda/Tuist/ProjectDescriptionHelpers/TargetDependency+Extension.swift
  GaeManda/Tuist/ResourceSynthesizers/Fonts.stencil
Labels: feature

#29 스냅킷 적용
  GaeManda/.swiftlint.yml
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInTabBarController.swift
  GaeManda/Projects/App/Sources/LoggedIn/Widgets/TabBarButton.swift
  GaeManda/Projects/DesignKit/Sources/OnBoardingTextField.swift
  GaeManda/Projects/DesignKit/Sources/OnBoardingTextView.swift
  GaeManda/Projects/DesignKit/Sources/UnderLineTextField.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseCell/TermsOfUseButton.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseCell/TermsOfUseCell.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/Widgets/OnBoardingView.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/SignInViewController.swift
Labels: feature
