Repository WalkingDogWithFriends/GaeManDa, pull requests merged in 2023-10, with the labels that each got.

#101 리블렛 이름 변경 및 모듈 위치 변경
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInComponent.swift
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInRouter.swift
  GaeManda/Projects/Data/DataMapper/Dummy.swift
  GaeManda/Projects/Data/Project.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/GMDProfileUseCase.swift
  GaeManda/Projects/Domain/Project.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/GMDProfileUseCaseImpl.swift
  GaeManda/Projects/Presentation/GMDMap/Implementations/DogsOnAroundBuilder.swift
  GaeManda/Projects/Presentation/GMDMap/Implementations/DogsOnAroundInteractor.swift
  GaeManda/Projects/Presentation/GMDMap/Implementations/DogsOnAroundRouter.swift
  GaeManda/Projects/Presentation/GMDMap/Implementations/DogsOnAroundViewController.swift
  GaeManda/Projects/Presentation/GMDMap/Implementations/GMDMapBuilder.swift
  GaeManda/Projects/Presentation/GMDMap/Implementations/GMDMapInteractor.swift
  GaeManda/Projects/Presentation/GMDMap/Implementations/GMDMapRouter.swift
  GaeManda/Projects/Presentation/GMDMap/Implementations/GMDMapViewController.swift
  GaeManda/Projects/Presentation/GMDMap/Interfaces/DogsOnAround.swift
  GaeManda/Projects/Presentation/GMDMap/Interfaces/GMDMap.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditBuilder.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/GMDProfileBuilder.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/GMDProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/GMDProfileRouter.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/GMDProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileBuilder.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditBuilder.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/GMDProfile.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/GMDProfileEdit.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/UserProfile.swift
  GaeManda/Tuist/ProjectDescriptionHelpers/TargetDependency+Extension.swift
Labels: style

#107 DropDownView 구현
  GaeManda/Projects/Core/GMDExtensions/UIKit/UIWindow+Extension.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownButton.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownCell.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownListener.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownTableView.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownView.swift
Labels: feature

#112 온보딩 강아지 설정 UI작업 완료
  GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
  GaeManda/Projects/Core/GMDUtils/GMDTextFieldListener/GMDTextFieldListener.swift
  GaeManda/Projects/Core/GMDUtils/PassTouchesScrollView/PassTouchesScrollView.swift
  GaeManda/Projects/Core/GMDUtils/PassTouchesScrollView/PassTouchesScrollViewDelegate.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownListener.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownTableView.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownView.swift
  GaeManda/Projects/DesignKit/Sources/TextField/GMDTextField.swift
  GaeManda/Projects/DesignKit/Sources/TextField/UnderLineTextField.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewModel.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/Widgets/OnBoardingView.swift
Labels: feature

#113 온보딩 강아지 설정 인프라 수정
  GaeManda/Projects/Core/GMDExtensions/RIBs/ViewControllable+Extension.swift
  GaeManda/Projects/Core/GMDExtensions/UIKit/UILabel+Extension.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/DogSetting.swift
Labels: infra, feature

#117 DropDownView 리팩토링
  GaeManda/Projects/DesignKit/Sources/DropDown/AnchorView.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownButton.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownListener.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownTableView.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownView.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
Labels: feature

#119 온보딩 강아지 설정 UI 로직
  GaeManda/Projects/DesignKit/Sources/Button/ConfirmButton.swift
  GaeManda/Projects/DesignKit/Sources/Button/GMDOptionButton.swift
  GaeManda/Projects/DesignKit/Sources/DropDown/DropDownView.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
Labels: feature

#102 API 기초 작업
  GaeManda/.swiftlint.yml
  GaeManda/Projects/App/Info.plist
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInComponent.swift
  GaeManda/Projects/Data/DTO/DogDTO/DogRequestDTO.swift
  GaeManda/Projects/Data/DTO/DogDTO/DogResponseDTO.swift
  GaeManda/Projects/Data/DTO/NewDogDTO/NewDogRequestDTO.swift
  GaeManda/Projects/Data/DTO/NewDogDTO/NewDogResponseDTO.swift
  GaeManda/Projects/Data/DTO/UpdateDogDTO/UpdateDogRequestDTO.swift
  GaeManda/Projects/Data/DTO/UpdateDogDTO/UpdateDogResponseDTO.swift
  GaeManda/Projects/Data/DTO/UpdateUserDTO/UpdateUserReqeustDTO.swift
  GaeManda/Projects/Data/DTO/UpdateUserDTO/UpdateUserResponseDTO.swift
  GaeManda/Projects/Data/DTO/UserDTO/UserRequestDTO.swift
  GaeManda/Projects/Data/DTO/UserDTO/UserResponseDTO.swift
  GaeManda/Projects/Data/DTO/UserProfileDTO/UserProfilePatchReqeustDTO.swift
  GaeManda/Projects/Data/DTO/UserProfileDTO/UserProfileResponseDTO.swift
  GaeManda/Projects/Data/DataMapper/DogDataMapper.swift
  GaeManda/Projects/Data/DataMapper/Dummy.swift
  GaeManda/Projects/Data/DataMapper/UserDataMapper.swift
  GaeManda/Projects/Data/GMDNetwork/BaseResponse.swift
  GaeManda/Projects/Data/GMDNetwork/HTTP/BaseResponseDTO.swift
  GaeManda/Projects/Data/GMDNetwork/HTTP/HTTPMethod.swift
  GaeManda/Projects/Data/GMDNetwork/Provider.swift
  GaeManda/Projects/Data/GMDNetwork/VoidResponse.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogRepositoryImpl.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/UserRepositoryImpl/UserAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/UserRepositoryImpl/UserRepositoryImpl.swift
  GaeManda/Projects/Domain/Interfaces/Repository/DogReposiotry.swift
  GaeManda/Projects/Domain/Interfaces/Repository/UserRepository.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/GMDProfileUseCase.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/GMDProfileUseCaseImpl.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditInteractor.swift
Labels: feature

#120 온보딩에 달력 바텀시트 연결
  GaeManda/Projects/App/Sources/AppRootComponent.swift
  GaeManda/Projects/App/Sources/AppRootInteractor.swift
  GaeManda/Projects/App/Sources/AppRootRouter.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutBuilder.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutComponent.swift
  GaeManda/Projects/Core/GMDExtensions/Foundation/Date+Extension.swift
  GaeManda/Projects/DesignKit/Resources/Colors/Colors.xcassets/Gray/DimmedColor.colorset/Contents.json
  GaeManda/Projects/DesignKit/Sources/BottomSheet/BottomSheetViewController.swift
  GaeManda/Projects/DesignKit/Sources/DatePicker/BirthdayPicker.swift
  GaeManda/Projects/DesignKit/Sources/DatePicker/BirthdayPickerBuilder.swift
  GaeManda/Projects/DesignKit/Sources/DatePicker/BirthdayPickerInteractor.swift
  GaeManda/Projects/DesignKit/Sources/DatePicker/BirthdayPickerRouter.swift
  GaeManda/Projects/DesignKit/Sources/DatePicker/BirthdayPickerViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
Labels: feature

#121 약관 동의 버튼 로직 구현
  GaeManda/.swiftlint.yml
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewModel.swift
Labels: feature

#123 지도에 현재위치를 표시하는 기능 추가
  GaeManda/Projects/App/Info.plist
  GaeManda/Projects/App/Sources/AppRootRouter.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutRouter.swift
  GaeManda/Projects/App/xcconfigs/GaeManda.shared.xcconfig
  GaeManda/Projects/Core/GMDExtensions/Rx/CoreLocation/Helpers.swift
  GaeManda/Projects/Core/GMDExtensions/Rx/CoreLocation/RxCLLocationManagerDelegateProxy.swift
  GaeManda/Projects/Core/GMDExtensions/Rx/ObservableType+Extension.swift
  GaeManda/Projects/Core/GMDExtensions/Rx/Reactive/CLLocation+Reactive.swift
  GaeManda/Projects/DesignKit/Sources/TextField/GMDTextField.swift
  GaeManda/Projects/DesignKit/Sources/TextField/UnderLineTextField.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingBuilder.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/AddressSetting.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/DetailAddressSetting.swift
  GaeManda/Projects/Presentation/OnBoarding/Project.swift
  GaeManda/Tuist/Dependencies.swift
  GaeManda/Tuist/ProjectDescriptionHelpers/TargetDependency+Extension.swift
Labels: feature
