Repository WalkingDogWithFriends/GaeManDa, pull requests merged in 2023-09, with the labels that each got.

#56 강아지 수정 Interactor 작업
  GaeManda/Projects/Core/GMDExtensions/UIViewController+Extensions.swift
  GaeManda/Projects/Data/DTO/Sources/DogDTO/DogResponseDTO.swift
  GaeManda/Projects/Data/DTO/Sources/UpdateDogDTO/UpdateDogRequestDTO.swift
  GaeManda/Projects/Data/DTO/Sources/UpdateDogDTO/UpdateDogResponseDTO.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogAPI.swift
  GaeManda/Projects/Data/RepositoryImpl/Sources/DogRepositoryImpl/DogRepositoryImpl.swift
  GaeManda/Projects/Domain/Entity/Dog.swift
  GaeManda/Projects/Domain/Interfaces/Repository/DogReposiotry.swift
  GaeManda/Projects/Domain/Interfaces/UseCase/UserProfileUseCase.swift
  GaeManda/Projects/Domain/UseCaseImpl/Sources/UserProfileUseCaseImpl.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditBuilder.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/ViewModel/DogDashBoardViewModel.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/ViewModel/TextFieldModeViewModel.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/Widgets/DogProfileDashBoardCell.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/Widgets/DogProfileEditScrollView.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileRouter.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogsCollectionViewCell.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/DogProfileEdit.swift
Labels: feature

#66 AddressSettingViewController 키보드 리스너 수정 적용
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
Labels: feature

#65 ThirdDogSettingViewController 리팩토링
  GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
  GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
  GaeManda/Projects/Domain/Entity/Dog.swift
  GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
Labels: refactoring

#64 SecondDogSettingViewController 리팩토링
  GaeManda/Projects/Core/GMDExtensions/String+Extension.swift
  GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
  GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
  GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
  GaeManda/Projects/Domain/Entity/Dog.swift
  GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
Labels: refactoring

#63 FirstDogSettingViewController 리팩토링
  GaeManda/Projects/Core/GMDExtensions/String+Extension.swift
  GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
  GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
  GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
  GaeManda/Projects/Domain/Entity/Dog.swift
  GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
Labels: refactoring

#62 유저 프로필 화면 리팩토링
  GaeManda/Projects/Core/GMDExtensions/String+Extension.swift
  GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
  GaeManda/Projects/Core/GMDUtils/Base/BaseViewController.swift
  GaeManda/Projects/Core/GMDUtils/KeyboardListener.swift
  GaeManda/Projects/DesignKit/Sources/Button/ConfirmButton.swift
  GaeManda/Projects/DesignKit/Sources/UnderLineTextField.swift
  GaeManda/Projects/Domain/Entity/Dog.swift
  GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
Labels: refactoring

#70 유저 프로필 화면 UI 수정
  GaeManda/Projects/DesignKit/Sources/RoundImageView.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/ViewModel/DogsCarouselViewModel.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogPageControl.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/IndicatorView.swift
Labels: feature

#72 강아지 추가 View UI작업
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInComponent.swift
  GaeManda/Projects/Core/GMDUtils/GMDTextFieldListener.swift
  GaeManda/Projects/DesignKit/Sources/GMDTextField.swift
  GaeManda/Projects/DesignKit/Sources/GMDTextView.swift
  GaeManda/Projects/DesignKit/Sources/UnderLineTextField.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/ViewModel/TextFieldModeViewModel.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileBuilder.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileRouter.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileBuilder.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileRouter.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/ViewModel/ScollViewUIComponentMode.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogProfileScrollView.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogsCollectionViewCell.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/DogProfileEdit.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/NewDogProfile.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/UserProfileEdit.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
Labels: feature

#79 빌드 오류 수정
  GaeManda/Projects/Core/Project.swift
Labels: bug

#80 SignIn 리블렛 수정 및 UI작업
  GaeManda/Projects/App/Sources/AppRootComponent.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutBuilder.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutComponent.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutInteractor.swift
  GaeManda/Projects/App/Sources/LoggedOut/LoggedOutRouter.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/SignInBuilder.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/SignInInteractor.swift
  GaeManda/Projects/Presentation/SignIn/Implementations/SignInViewController.swift
Labels: feature

#88 이미지 선택 기능 구현
  GaeManda/Projects/Core/GMDExtensions/PHPickerResult+Extension.swift
  GaeManda/Projects/Core/GMDUtils/UIViewController+Utils.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/Widgets/OnBoardingView.swift
Labels: feature

#87 이미지 에셋 적용
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInTabBarController.swift
  GaeManda/Projects/Core/GMDUtils/UIViewController+Utils.swift
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_calendar.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_calendar.imageset/icon_calendar.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_camera_on.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_camera_on.imageset/icon_camera_on.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_chat.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_chat.imageset/icon_chat.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_check_gray.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_check_gray.imageset/icon_check_gray.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_check_green.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_check_green.imageset/icon_check_green.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_chevron_left.imageset/icon_chevron_left.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_close_round.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_close_round.imageset/icon_close_round.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_delete.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_delete.imageset/icon_delete.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_gps.imageset/icon_gps.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_highlight.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_highlight.imageset/icon_highlight.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_more.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_more.imageset/icon_more.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_notification.imageset/icon_notification.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_plus_circle.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_plus_circle.imageset/icon_plus_circle.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_plus_circle_big.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_plus_circle_big.imageset/icon_plus_circle_big.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_search.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_search.imageset/icon_search.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_send_green.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_send_green.imageset/icon_send_green.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_settings.imageset/icon_settings.pdf
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_walking_dog.imageset/Contents.json
  GaeManda/Projects/DesignKit/Resources/Images/Images.xcassets/icon_walking_dog.imageset/icon_walking_dog.pdf
  GaeManda/Projects/DesignKit/Sources/NavigationBar/GMDNavigationBar.swift
  GaeManda/Projects/DesignKit/Sources/NavigationBar/GMDNavigationItem.swift
  GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/ChattingViewController.swift
  GaeManda/Projects/Presentation/Chatting/Implementations/Chatting/Widgets/ChattingTextView.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/Widgets/DogProfileScrollView.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseCell/TermsOfUseButton.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
Labels: design

#96 Swipe back 제스쳐 적용
  GaeManda/Projects/Core/GMDExtensions/String+Extension.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileInteractor.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileRouter.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/DogProfileEdit.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/NewDogProfile.swift
  GaeManda/Projects/Presentation/GMDProfile/Interfaces/UserProfileEdit.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/AddressSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/DogSettingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/FirstDogSetting/FirstDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/SecondDogSetting/SecondDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/DogSetting/ThirdDogSetting/ThirdDogSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingRouter.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingInteractor.swift
  GaeManda/Projects/Presentation/OnBoarding/Implementations/UserSetting/UserSettingViewController.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/AddressSetting.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/DogSetting.swift
  GaeManda/Projects/Presentation/OnBoarding/Interfaces/UserSetting.swift
Labels: feature

#91 TabBar Profile Image 외부변경가능하도록 수정
  GaeManda/Projects/App/Sources/LoggedIn/LoggedInTabBarController.swift
  GaeManda/Projects/App/Sources/LoggedIn/Widgets/TabBarButton.swift
  GaeManda/Projects/Core/GMDUtils/FloatingTabBarPresentable.swift
Labels: feature

#100 GMDProfile 이미지 선택 기능 적용
  GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/NewDogProfile/NewDogProfileViewController.swift
  GaeManda/Projects/Presentation/GMDProfile/Implementations/UserProfileEdit/UserProfileEditViewController.swift
Labels: feature
